name: Publish urh-react-hooks to NPM

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - name: install deps
        run: |
          yarn install
          ls -la

      - name: build urh-react-hooks
        run: |
          yarn build
          cp README.md packages/urh-react-hooks/
          cd packages/urh-react-hooks
          ls -la

      - name: publish to npm registry
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
